name: build calibre (manual)
on:
  workflow_dispatch:
    
jobs:
    build:
        name: Build on ubuntu-latest
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v3
              with:
                fetch-depth: 10

            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: 3.8

            - name: Install calibre dependencies
              run:
                  python setup/unix-ci.py install

            - name: Bootstrap calibre
              run:
                  python setup/unix-ci.py bootstrap

            - name: Test calibre
              env:
                PYTHONWARNINGS: error
                CALIBRE_SHOW_DEPRECATION_WARNINGS: 1
              run:
                  python setup/unix-ci.py test
  
            - name: Build calibre
              run:
                  python setup.py build
                  python setup.py gui

            - name: Install calibre
              run:
                  python setup.pyinstall # binaries
                  # sudo python setup.py develop # source

